# Generated by Django 4.1.3 on 2022-11-27 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vardas')),
                ('last_name', models.CharField(max_length=50, verbose_name='Pavardė')),
                ('biography', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Biografija')),
                ('author_photo', models.ImageField(blank=True, max_length=50, null=True, upload_to='authors/Photo/', verbose_name='Nuotrauka')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Knygos pavadinimas')),
                ('year', models.CharField(blank=True, max_length=4, null=True, verbose_name='Metai')),
                ('desc', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Aprašymas')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='books/pdfs/', verbose_name='Knygos pdf')),
                ('cover', models.ImageField(blank=True, max_length=50, null=True, upload_to='books/covers/', verbose_name='Viršelis')),
                ('uploaded_by', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='bookcase.author')),
            ],
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentReview', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rašyti komentarą')),
                ('pdfReview', models.FileField(blank=True, null=True, upload_to='books/reviews/', verbose_name='Įkelti recenzijos failą')),
                ('review_date', models.DateTimeField(auto_now_add=True, verbose_name='Įrašo data')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_reviews', to='bookcase.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['review_date'],
            },
        ),
    ]
