# Generated by Django 4.1.3 on 2022-11-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='comentReview',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Rašyti komentarą'),
        ),
    ]
